from __future__ import annotations

"""Reference implementation of GEGLU.
Source: local_attention/transformer.py (lines 186-189).
Do not modify — your optimized version belongs in solution.py.
"""
# Auto-generated by kernel-synth env_builder.
# If imports fail, install the source repo or stub the missing names.
import math
import torch
import torch.nn as nn
import torch.nn.functional as F

# --- imports lifted from the source file (filtered) ---
import torch.nn.functional as F
from torch.nn import Module, ModuleList

class GEGLU(Module):
    def forward(self, x):
        x, gate = x.chunk(2, dim = -1)
        return x * F.gelu(gate)
